add_newline = false
# [character]
# success_symbol = "$"
[git_branch]
symbol = "🌱 "
[directory]
truncate_to_repo = false
truncation_length = 128
[hostname]
disabled = false
format = "[$hostname](bold red) "
ssh_only = false
[username]
disabled = false
show_always = true
[terraform]
disabled = false
